name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm ci
    - name: npm run build
      run: npm run build
    - name: npm run lint
      run: npm run lint
    - name: npm run format-check
      run: npm run format-check
